### ISSUE TITLE
Isolation Forest model selection

### ISSUE THREAD

**Issue by jfear** [jfear/ncbi_remap#113]
### Story
I need to finalize the Isolation Forest model used for Library Strategy. I want to validate that the model is working well and integrate the final version into the workflow.

### Tasks
- [x] Use WGS, instead of ChIP-Seq, for validation. I think Pol II chip may throw things off.
- [x] Feature engineering
    - Aggregate gene body coverage into tertile. Currently, gene body coverage is in centiles which are just too highly correlated. I think it is better to present as 5', 3' and middle. 
- [x] Change model to run on an individual feature. I want to try to run more trees, but using individual features. This is the default and may work better once I do some feature engineering.
- [x] Set contamination rate. Right now I am using "auto", but I think realistically a contamination rate of 1% is going to work the best.
- [x] Use SHAP values to decide if there are additional features that can be removed or tweaked.

**Comment by jfear** [comment]
The key here was feature selection. The model is performing better, using mixin testing, once I reduced to key features.
