### ISSUE TITLE
Identify high quality RNA-seq samples in SRA.

### ISSUE THREAD

**Issue by jfear** [jfear/ncbi_remap#30]
### Story
I need a set of high quality samples from SRA. These samples should be RNA-seq and have the majority of reads aligning uniquely to the D. mel genome. To identify RNA-seq samples, I need a set of criteria that separate RNA-seq samples from other types of sequencing technologies. 

### Questions and Tasks (https://workflowy.com/s/DzPZ.MLSuWfXtiU)
- [x] How many highly stranded datasets are there?
- [ ] 

### List of criteria
- [ ] Strandedness
- [ ] 

### Definition of done
- [ ] Have a list of criteria which to separate high quality samples.
- [ ] Have code to aggregate these criteria.
- [ ] Have code to summarize these criteria.
- [ ] Have figure(s) demonstrating these criteria.
- [ ] Written explanation of methods and results for sample selection.
