### ISSUE TITLE
Library Complexity

### ISSUE THREAD

**Issue by jfear** [jfear/ncbi_remap#50]
### Story
For RNA-Seq library complexity is a common metric. Complexity can also help inform the library strategy (i.e., RNA-Seq, ChIP-Seq, DNA-Seq). I am interested in using complexity for two purposes: first I want to use complexity to help separate library strategies, second I want to use complexity as a QC metric to identify samples that suffer from large amounts of PCR bias. 

### Questions and Tasks
- [ ] Can we use library complexity as a feature for strategy selection?
- [ ] Can we use library complexity as a QC metric?

### Definition of done
- [ ] Answers to the above questions and their outputs.
